### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by jyh3690** [dyhBUPT/StrongSORT#25]
when i run:"python strong_sort.py MOT17 val --BoT --ECC --NSA --EMA --MC --woC --AFLink --GSI"
there is an error as below:
processing the 1th video MOT17-02-FRCNN...
Traceback (most recent call last):
  File "strong_sort.py", line 46, in <module>
    linker.link()
  File "/home/gaoyelu/jyh/StrongSORT/AFLink/AppFreeLink.py", line 87, in link
    cost = self.predict(info_i, info_j)
  File "/home/gaoyelu/jyh/StrongSORT/AFLink/AppFreeLink.py", line 62, in predict
    score = self.model(track1, track2)[0, 1].detach().cpu().numpy()
  File "/home/usr/local/anaconda3/envs/strongsort/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gaoyelu/jyh/StrongSORT/AFLink/model.py", line 85, in forward
    x1 = self.TemporalModule_1(x1)  # [B,1,30,3] -> [B,256,6,3]
  File "/home/usr/local/anaconda3/envs/strongsort/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/usr/local/anaconda3/envs/strongsort/lib/python3.6/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/usr/local/anaconda3/envs/strongsort/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gaoyelu/jyh/StrongSORT/AFLink/model.py", line 27, in forward
    x = self.conv(x)
  File "/home/usr/local/anaconda3/envs/strongsort/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/usr/local/anaconda3/envs/strongsort/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/usr/local/anaconda3/envs/strongsort/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: no kernel image is available for execution on the device

**Comment by dyhBUPT** [comment]
It seems that the PyTorch doesn't work well with the CUDA.
Please check that you have installed the PyTorch and CUDA correctly.

Best wishes.

**Comment by jyh3690** [comment]
thanks,bro
