### ISSUE TITLE
KeyError: 'MOT17-02-DPM'

### ISSUE THREAD

**Issue by flag16** [dyhBUPT/StrongSORT#86]
G:/StrongSORT-master/strong_sort.py MOT17 val --ECC

Traceback (most recent call last):
  File "G:/StrongSORT-master/strong_sort.py", line 33, in <module>
    display=False
  File "G:\StrongSORT-master\deep_sort_app.py", line 213, in run
    visualizer.run(frame_callback)
  File "G:\StrongSORT-master\application_util\visualization.py", line 80, in run
    frame_callback(self, self.frame_idx)
  File "G:\StrongSORT-master\deep_sort_app.py", line 187, in frame_callback
    tracker.camera_update(sequence_dir.split('\\')[-1], frame_idx)
  File "G:\StrongSORT-master\deep_sort\tracker.py", line 57, in camera_update
    track.camera_update(video, frame)
  File "G:\StrongSORT-master\deep_sort\track.py", line 141, in camera_update
    dict_frame_matrix = opt.ecc[video]
KeyError: 'MOT17-02-DPM'

**Comment by flag16** [comment]
Thank you for your great work ! 
When I run strong_sort.py MOT17 val --ECC  ,
it displays    KeyError: 'MOT17-02-DPM'
Why does it happen ?

**Comment by dyhBUPT** [comment]
Hi, thanks for your interest in our work.

That's because only sequences `xxx-xx-FRCNN` are included.

**Comment by flag16** [comment]
Thank you very much, I have solved the problem. I got the full results using ECC but I didn't replace your data

**Comment by SoloistZH** [comment]
> Hi, thanks for your interest in our work.
> 
> That's because only sequences are included.`xxx-xx-FRCNN`
Hi, thanks for your great work! I also got a similar error when reproducing your results. The error information is as follows:
Traceback (most recent call last):
File "strong_sort.py", line 24, in <module>
run(
File "E:\My_Research\StrongSORT-master\deep_sort_app.py", line 213, in run
visualizer.run(frame_callback)
File "E:\My_Research\StrongSORT-master\application_util\visualization.py", line 100, in run
self.viewer.run(lambda: self._update_fun(frame_callback))
File "E:\My_Research\StrongSORT-master\application_util\image_viewer.py", line 305, in run
self._terminate = not self._user_fun()
File "E:\My_Research\StrongSORT-master\application_util\visualization.py", line 100, in <lambda>
self.viewer.run(lambda: self._update_fun(frame_callback))
File "E:\My_Research\StrongSORT-master\application_util\visualization.py", line 105, in _update_fun
frame_callback(self, self.frame_idx)
File "E:\My_Research\StrongSORT-master\deep_sort_app.py", line 187, in frame_callback
tracker.camera_update(sequence_dir.split('/')[-1], frame_idx)
File "E:\My_Research\StrongSORT-master\deep_sort\tracker.py", line 57, in camera_update
track.camera_update(video, frame)
File "E:\My_Research\StrongSORT-master\deep_sort\track.py", line 141, in camera_update
dict_frame_matrix = opt.ecc[video]
KeyError: 'MOT17\\train\\MOT17-02-FRCNN'

I still don't quite understand what you mean by this sentence. Could you please explain it in more detail? Thank you!
